# =============================================================================
# I2C Configuration
# =============================================================================
I2C_RETRIES = 3
RETRY_DELAY = 0.2
OPERATION_TIMEOUT = 5
READ_TIMEOUT = 1.0

# =============================================================================
# Sensor Offsets (auto-generated by calibration)
# =============================================================================
OFFSET = {'vl53l0x_0': -62.967, 'vl53l0x_1': -53.667}

# =============================================================================
# TCA9548A Multiplexer Channel Assignments
# =============================================================================
VL53_CHANNEL_1 = 0
VL53_CHANNEL_2 = 1
ADXL_CHANNEL   = 2

# =============================================================================
# Sensor I2C Addresses
# =============================================================================
VL53_ADDRESS  = 0x29
ADXL_ADDRESS  = 0x53

# =============================================================================
# Sensor Name Constants
#   Use these everywhere instead of bare string literals.
# =============================================================================
SENSOR_VL53_0 = "vl53l0x_0"
SENSOR_VL53_1 = "vl53l0x_1"
SENSOR_ADXL   = "adxl345"
SENSOR_MUX    = "mux"

# Convenience tuple for iterating over distance sensors only
DISTANCE_SENSORS = (SENSOR_VL53_0, SENSOR_VL53_1)

# =============================================================================
# VL53L0X Sensor Configuration
# =============================================================================
VL53_TIMING_BUDGET = 100000   # microseconds
VL53_RATE_LIMIT    = 0.25     # MCPS
VL53_SIGMA_LIMIT   = 9        # millimetres

# =============================================================================
# Serial / UART Configuration
# =============================================================================
SERIAL_PORT     = '/dev/serial0'
SERIAL_BAUDRATE = 2400
SERIAL_TIMEOUT  = 1           # seconds

# =============================================================================
# MQTT Configuration
# =============================================================================
MQTT_BROKER = "192.168.1.138"
MQTT_PORT = 1883
MQTT_TOPIC_COMMAND = "home/desk/command"
MQTT_TOPIC_STATUS = "home/desk/status"
MQTT_TOPIC_FEEDBACK = "home/desk/feedback"
MQTT_USERNAME = "eceMos"
MQTT_PASSWORD = "eceMos1"
MQTT_PRESET_FILE = "desk_presets.json"
MQTT_HEARTBEAT_INTERVAL = 60  # seconds

# =============================================================================
# Motor Control Commands  (3-byte packets: header, command, checksum)
# =============================================================================
CMD_ALL_OFF = b'\x5a\x00\x5a'   # Stop all motors

CMD_M1_EXTEND  = b'\x5a\x01\x5b'   # Motor 1 extend  (OUT)
CMD_M1_RETRACT = b'\x5a\x02\x5c'   # Motor 1 retract (IN)

CMD_M2_EXTEND  = b'\x5a\x04\x5e'   # Motor 2 extend  (OUT)
CMD_M2_RETRACT = b'\x5a\x08\x62'   # Motor 2 retract (IN)

CMD_M3_EXTEND  = b'\x5a\x10\x6a'   # Motor 3 extend  (OUT)
CMD_M3_RETRACT = b'\x5a\x20\x7a'   # Motor 3 retract (IN)

# Map each motor-driving sensor to its motor commands for use in motor_control.py
SENSOR_MOTOR_COMMANDS = {
    SENSOR_ADXL: {"extend": CMD_M1_EXTEND, "retract": CMD_M1_RETRACT},
    SENSOR_VL53_0: {"extend": CMD_M2_EXTEND, "retract": CMD_M2_RETRACT},
    SENSOR_VL53_1: {"extend": CMD_M3_EXTEND, "retract": CMD_M3_RETRACT},
}

# =============================================================================
# Position Limits  (millimetres) — VL53L0X actuators
# =============================================================================
MIN_POSITION = 0
MAX_POSITION = 390

# =============================================================================
# Angle Limits (degrees) — ADXL345 actuator (Motor 3)
#
#   The actuator has a 200 mm stroke.  Map that stroke onto an angle window
#   that keeps the actuator safely within its mechanical limits.
#
#     MIN_ANGLE_DEG : angle at which the actuator is fully retracted
#     MAX_ANGLE_DEG : angle at which the actuator is fully extended
#
#   Convention: 0° = upside down, 90° = perpendicular, 180° = right-side up.
#   Adjust these limits to match your physical installation.
# =============================================================================
MIN_ANGLE_DEG = 60.0    # fully retracted — adjust to your rig
MAX_ANGLE_DEG = 120.0   # fully extended  — adjust to your rig
